const {test,expect}=require('@playwright/test');
const {pathToFileURL}=require('node:url');
const path=require('node:path');
const url=pathToFileURL(path.resolve(__dirname,'../../index.html')).href;
test('graph form preserves invalid drafts and layout controls preserve snapshot progress',async({page})=>{
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.clock.install();
  await page.goto(url+'#/lab/bfs');
  await page.locator('#input-nodes').fill('A B C');
  await page.locator('#input-edges').fill('A B 0\nB C 2');
  await page.locator('#input-direction').selectOption('directed');
  await page.locator('#input-start').fill('C');
  await page.locator('#applyInputBtn').click();
  await page.locator('#playBtn').click();await page.clock.runFor(10000);
  await expect(page.locator('#stepMessage')).toContainText('遍历完成');
  const before=await page.locator('#stateTables').innerText();
  const counter=await page.locator('#stepCounter').innerText();
  await page.getByRole('button',{name:'移动所选节点 →',exact:true}).click();
  await expect(page.locator('#stepCounter')).toHaveText(counter);
  expect(await page.locator('#stateTables').innerText()).toBe(before);
  await page.locator('#input-start').fill('Z');await page.locator('#applyInputBtn').click();
  await expect(page.locator('#inputError')).toContainText('起点');
  expect(await page.locator('#stateTables').innerText()).toBe(before);
  await page.locator('#presetInputBtn').click();
  await expect(page.locator('#input-start')).toHaveValue('A');
  await expect(page.locator('#stepCounter')).toHaveText(/^01/);
  await page.evaluate(()=>{location.hash='#/lab/kmp';});
  await expect(page.locator('#layoutControls')).toBeHidden();
  expect(errors).toEqual([]);
});
test('binary search custom input rejects unsorted data and preserves zero target',async({page})=>{
  await page.goto(url+'#/lab/binary-search');
  await page.locator('#input-values').fill('0,2,4');
  await page.locator('#input-target').fill('0');
  await page.locator('#applyInputBtn').click();
  const before=await page.locator('#stateTables').innerText();
  await page.locator('#input-values').fill('2,0,4');
  await page.locator('#applyInputBtn').click();
  await expect(page.locator('#inputError')).toContainText('非递减');
  expect(await page.locator('#stateTables').innerText()).toBe(before);
  while(await page.locator('#nextBtn').isEnabled())await page.locator('#nextBtn').click();
  await expect(page.locator('#stepMessage')).toContainText('下标为 0');
});
