const test=require('node:test');
const assert=require('node:assert/strict');
const A=require('../assets/js/algorithms/advanced-trees.js');
const experiments=require('../content/advanced-tree-experiments.js');
function inspect(s,balanced=false){const {root,nodes}=s.tree,seen=new Set(),depths=[],all=[];if(!root){assert.equal(Object.keys(nodes).length,0);return [];}
  function walk(id,parent,lo,hi,depth){assert.ok(nodes[id]);assert.ok(!seen.has(id),'acyclic unique ownership');seen.add(id);const n=nodes[id];assert.equal(n.parent,parent);assert.deepEqual(n.keys,[...n.keys].sort((a,b)=>a-b));assert.equal(new Set(n.keys).size,n.keys.length);n.keys.forEach(x=>assert.ok(x>=lo&&x<hi));const kids=n.children.filter(Boolean);
    if(s.type==='red-black'){assert.equal(n.children.length,2);const l=n.children[0]?walk(n.children[0],id,lo,n.keys[0],depth+1):1;all.push(n.keys[0]);const r=n.children[1]?walk(n.children[1],id,n.keys[0]+1,hi,depth+1):1;if(balanced){assert.equal(l,r,'black height');if(n.color==='red')kids.forEach(k=>assert.equal(nodes[k].color,'black'));}return l+(n.color==='black'?1:0);}
    if(balanced){assert.ok(n.keys.length<=3);if(parent)assert.ok(n.keys.length>=1);}
    if(n.leaf){assert.equal(kids.length,0);depths.push(depth);all.push(...n.keys);return n.keys[0];}
    assert.equal(kids.length,n.keys.length+1);let minimum;
    kids.forEach((k,i)=>{const min=walk(k,id,i?n.keys[i-1]+(s.type==='b-tree'?1:0):lo,i<n.keys.length?n.keys[i]:hi,depth+1);if(i===0)minimum=min;else if(s.type==='b-plus')assert.equal(min,n.keys[i-1],'separator equals right subtree minimum');if(s.type==='b-tree'&&i<n.keys.length)all.push(n.keys[i]);});return minimum;
  }
  walk(root,null,-Infinity,Infinity,0);assert.equal(seen.size,Object.keys(nodes).length,'no orphan nodes');if(balanced&&s.type==='red-black')assert.equal(nodes[root].color,'black');if(s.type!=='red-black')assert.equal(new Set(depths).size,1,'equal leaf depth');if(s.type==='b-plus'){let n=nodes[root];while(!n.leaf)n=nodes[n.children[0]];const linked=[],ids=new Set();while(n){assert.ok(!ids.has(n.id));ids.add(n.id);linked.push(...n.keys);n=n.next?nodes[n.next]:null;}assert.deepEqual(linked,all);assert.equal(ids.size,Object.values(nodes).filter(n=>n.leaf).length);}return all;
}
const sequences=[[1],[3,2,1],[1,2,3],[3,1,2],[1,3,2],[10,20,30,15,25,5,1,8,12,18,22,28],Array.from({length:12},(_,i)=>i),Array.from({length:12},(_,i)=>11-i),[-999,999,0,-8,8,7,-7,6,-6,5,-5,4]];
let seed=177;for(let j=0;j<70;j++){const list=Array.from({length:12},(_,i)=>i-6);for(let i=list.length-1;i>0;i--){seed=(seed*1664525+1013904223)>>>0;const k=seed%(i+1);[list[i],list[k]]=[list[k],list[i]];}sequences.push(list);}
for(const name of Object.keys(A))test(name+' maintains structural links and completed invariants across insertion orders',()=>{for(const values of sequences){const steps=A[name](values,values[0]),copy=JSON.stringify(steps[0]);steps.forEach(st=>{assert.ok(Object.isFrozen(st.state));assert.ok(st.line>=1&&st.line<=10);inspect(st.state,['balanced','done','search','found','missing'].includes(st.state.phase));});assert.deepEqual(inspect(steps.at(-1).state,true),[...new Set(values)].sort((a,b)=>a-b));assert.ok(steps.at(-1).state.found);assert.equal(JSON.stringify(steps[0]),copy);assert.notEqual(steps[0].state.tree,steps[1].state.tree);assert.equal(A[name](values,998).at(-1).state.found,false);}});
test('duplicates are explicitly rejected; optional query; validation',()=>{for(const fn of Object.values(A)){const out=fn([2,2,1]);assert.ok(out.some(s=>s.state.phase==='duplicate'));assert.deepEqual(inspect(out.at(-1).state,true),[1,2]);assert.equal(out.at(-1).state.found,null);for(const values of [[],[1.2],[1000],Array(13).fill(1)])assert.throws(()=>fn(values));assert.throws(()=>fn([1],NaN));}});
test('teaching snapshots include rotations, recolors and splits',()=>{assert.ok(A.redBlack([3,2,1]).some(s=>s.state.phase==='rotate'));assert.ok(A.redBlack([3,2,1]).some(s=>s.state.phase==='recolor'));for(const fn of [A.bTree,A.bPlus])assert.ok(fn(sequences[5]).some(s=>s.state.phase==='split'));});
test('experiment inputs preserve zero and negatives, reject malformed query, and map to generators',()=>{for(const e of experiments){assert.equal(e.visualizer,'multi-tree');assert.equal(e.input.parse({values:'1, 2',target:'oops'}).ok,false);assert.equal(e.input.parse({values:'',target:''}).ok,false);assert.equal(e.input.parse({values:'1.5',target:''}).ok,false);const p=e.input.parse({values:'0， -999, 999',target:'0'});assert.equal(p.ok,true);const steps=e.createSteps(p.value);assert.ok(steps.at(-1).state.found);assert.ok(e.describeState(steps.at(-1).state)[0].rows.length);}});
test('optional query highlights finish-building and validation exposes form message',()=>{for(const e of experiments){assert.ok(e.input.parse({values:'x'}).message);assert.ok(e.input.parse({values:'1',target:'x'}).message);assert.ok(e.input.hint.includes('重复'));assert.equal(e.createSteps({values:[1]}).at(-1).line,8);}});
test('renderer preserves lone child orientation and fits full-width negative keys',()=>{
  const scene=require('../assets/js/visualizers/canvas-scene.js'),render=require('../assets/js/visualizers/multi-tree-renderer.js'),original=scene.setup;
  const rects=[],labels=[],c=new Proxy({measureText:value=>({width:value.length*10}),fillRect:(x,y,w,h)=>rects.push({x,y,w,h}),fillText:(value,x,y)=>labels.push({value,x,y})},{get:(obj,key)=>key in obj?obj[key]:()=>{},set:(obj,key,value)=>(obj[key]=value,true)});
  scene.setup=()=>({c,w:1000,h:600});
  try{for(const [values,left] of [[[2,1],true],[[1,2],false]]){labels.length=0;rects.length=0;render({},A.redBlack(values).at(-1).state);const parent=labels.find(l=>l.value===String(values[0])),child=labels.find(l=>l.value===String(values[1]));assert.ok(left?child.x<parent.x:child.x>parent.x);}
    const state=A.bPlus([-999,-998,-997,-996]).find(s=>s.state.phase==='insert'&&Object.values(s.state.tree.nodes).some(n=>n.keys.length===4)).state;rects.length=0;render({},state);assert.ok(rects.some(r=>r.w>=('-999 | -998 | -997 | -996'.length*10+28)));
  }finally{scene.setup=original;}
});
