const test=require('node:test');
const assert=require('node:assert/strict');
const A=require('../assets/js/algorithms/advanced-trees.js');
const experiments=require('../content/advanced-tree-experiments.js');
const {CODE_LINES,inOrder,inspect,inspectSteps}=require('./tree-invariants.cjs');
const sequences=[[1],[3,2,1],[1,2,3],[3,1,2],[1,3,2],[10,20,30,15,25,5,1,8,12,18,22,28],Array.from({length:12},(_,i)=>i),Array.from({length:12},(_,i)=>11-i),[-999,999,0,-8,8,7,-7,6,-6,5,-5,4]];
let seed=177;for(let j=0;j<70;j++){const list=Array.from({length:12},(_,i)=>i-6);for(let i=list.length-1;i>0;i--){seed=(seed*1664525+1013904223)>>>0;const k=seed%(i+1);[list[i],list[k]]=[list[k],list[i]];}sequences.push(list);}
for(const name of Object.keys(A))test(name+' maintains structural links and completed invariants across insertion orders',()=>{for(const values of sequences){const steps=A[name](values,[],values[0]),copy=JSON.stringify(steps[0]);inspectSteps(name,steps);assert.deepEqual(inOrder(steps.at(-1).state),[...new Set(values)].sort((a,b)=>a-b));assert.ok(steps.at(-1).state.found);assert.equal(JSON.stringify(steps[0]),copy);assert.notEqual(steps[0].state.tree,steps[1].state.tree);assert.equal(A[name](values,[],998).at(-1).state.found,false);assert.ok(steps.every(st=>st.line>=1&&st.line<=CODE_LINES[name]));}});
test('duplicates are explicitly rejected; optional query; validation',()=>{for(const fn of Object.values(A)){const out=fn([2,2,1]);assert.ok(out.some(s=>s.state.phase==='duplicate'));assert.deepEqual(inOrder(out.at(-1).state),[1,2]);assert.equal(out.at(-1).state.found,null);for(const values of [[],[1.2],[1000],Array(13).fill(1)])assert.throws(()=>fn(values));assert.throws(()=>fn([1],[],NaN));}});
test('teaching snapshots include rotations, recolors, splits and deletes',()=>{assert.ok(A.redBlack([3,2,1]).some(s=>s.state.phase==='rotate'));assert.ok(A.redBlack([3,2,1]).some(s=>s.state.phase==='recolor'));for(const fn of [A.bTree,A.bPlus])assert.ok(fn(sequences[5]).some(s=>s.state.phase==='split'));assert.ok(A.redBlack(sequences[5],[sequences[5][0]]).some(s=>s.state.phase==='deleted'));for(const fn of [A.bTree,A.bPlus])assert.ok(fn(sequences[5],[sequences[5][0]]).some(s=>s.state.phase==='deleted'));});
test('experiment inputs preserve zero and negatives, reject malformed query, and map to generators',()=>{for(const e of experiments){assert.equal(e.visualizer,'multi-tree');assert.equal(e.input.parse({values:'1, 2',target:'oops'}).ok,false);assert.equal(e.input.parse({values:'',target:''}).ok,false);assert.equal(e.input.parse({values:'1.5',target:''}).ok,false);assert.equal(e.input.parse({values:'1, 2',deletes:'x'}).ok,false);assert.equal(e.input.parse({values:'1, 2, 3',deletes:'1, 4, 5'}).ok,true);const p=e.input.parse({values:'0， -999, 999',target:'0',deletes:'0'});assert.equal(p.ok,true);const steps=e.createSteps(p.value);assert.ok(steps.some(st=>st.state.phase==='deleted'));assert.ok(e.describeState(steps.at(-1).state)[0].rows.length);}});
test('optional query highlights finish-building and validation exposes form message',()=>{for(const e of experiments){assert.ok(e.input.parse({values:'x'}).message);assert.ok(e.input.parse({values:'1',target:'x'}).message);assert.ok(e.input.parse({values:'1',deletes:'x'}).message);assert.ok(e.input.hint.includes('重复'));assert.ok(e.input.hint.includes('删除'));assert.equal(e.createSteps({values:[1],deletes:[],target:undefined}).at(-1).line,CODE_LINES[['redBlack','bTree','bPlus'][experiments.indexOf(e)]]-1);}});
test('renderer preserves lone child orientation and fits full-width negative keys',()=>{
  const scene=require('../assets/js/visualizers/canvas-scene.js'),render=require('../assets/js/visualizers/multi-tree-renderer.js'),original=scene.setup;
  const rects=[],labels=[],c=new Proxy({measureText:value=>({width:value.length*10}),fillRect:(x,y,w,h)=>rects.push({x,y,w,h}),fillText:(value,x,y)=>labels.push({value,x,y})},{get:(obj,key)=>key in obj?obj[key]:()=>{},set:(obj,key,value)=>(obj[key]=value,true)});
  scene.setup=()=>({c,w:1000,h:600});
  try{for(const [values,left] of [[[2,1],true],[[1,2],false]]){labels.length=0;rects.length=0;render({},A.redBlack(values).at(-1).state);const parent=labels.find(l=>l.value===String(values[0])),child=labels.find(l=>l.value===String(values[1]));assert.ok(left?child.x<parent.x:child.x>parent.x);}
    const state=A.bPlus([-999,-998,-997,-996]).find(s=>s.state.phase==='insert'&&Object.values(s.state.tree.nodes).some(n=>n.keys.length===4)).state;rects.length=0;render({},state);assert.ok(rects.some(r=>r.w>=('-999 | -998 | -997 | -996'.length*10+28)));
  }finally{scene.setup=original;}
});
