const fs = require('node:fs');
const path = require('node:path');
const { writeCatalog } = require('./catalog.cjs');
const root = path.resolve(__dirname, '..');
const output = path.resolve(root, 'dist');
const marker = '.zhixu-generated';
const extensions = new Set(['.html', '.css', '.js', '.woff2', '.woff', '.ttf', '.svg', '.png', '.webp', '.ico']);

function copyRuntime(source, target) {
  if (!target.startsWith(output + path.sep)) throw new Error('发布路径越界');
  const stat = fs.lstatSync(source);
  if (stat.isSymbolicLink()) throw new Error('发布不接受符号链接：' + source);
  if (stat.isDirectory()) {
    fs.mkdirSync(target, { recursive: true });
    for (const entry of fs.readdirSync(source)) copyRuntime(path.join(source, entry), path.join(target, entry));
  } else if (extensions.has(path.extname(source))) {
    fs.mkdirSync(path.dirname(target), { recursive: true });
    fs.copyFileSync(source, target);
  }
}
function build() {
  writeCatalog();
  // Never clean an arbitrary directory or a user-owned folder without our marker.
  if (path.dirname(output) !== root || path.basename(output) !== 'dist') throw new Error('发布目录不安全');
  if (fs.existsSync(output)) {
    if (fs.lstatSync(output).isSymbolicLink() || !fs.existsSync(path.join(output, marker))) throw new Error('dist 不是本工具生成的目录，已停止以保护文件');
    fs.rmSync(output, { recursive: true, force: true });
  }
  fs.mkdirSync(output);
  fs.writeFileSync(path.join(output, marker), 'Generated by scripts/build.cjs. Do not edit release files.\n');
  copyRuntime(path.join(root, 'index.html'), path.join(output, 'index.html'));
  copyRuntime(path.join(root, 'platform'), path.join(output, 'platform'));
  const subjects = [['数据结构可视化', 'data-structures'], ['概率论可视化', 'probability'], ['计算机组成原理可视化', 'computer-organization'], ['操作系统可视化', 'operating-systems'], ['计算机网络可视化', 'computer-networks'], ['高等数学可视化', 'calculus'], ['线性代数可视化', 'linear-algebra']];
  for (const [source, id] of subjects) {
    const destination = path.join(output, 'subjects', id);
    for (const entry of ['index.html', 'assets', 'content']) copyRuntime(path.join(root, source, entry), path.join(destination, entry));
    const html = fs.readFileSync(path.join(destination, 'index.html'), 'utf8').replaceAll('../platform/', '../../platform/');
    fs.writeFileSync(path.join(destination, 'index.html'), html);
  }
  const config = path.join(output, 'platform/subjects.js');
  let source = fs.readFileSync(config, 'utf8');
  for (const [directory, id] of subjects) source = source.replaceAll(directory + '/index.html', 'subjects/' + id + '/index.html');
  fs.writeFileSync(config, source);
  return output;
}
module.exports = { build };
if (require.main === module) console.log('静态发布完成：' + build());
