(function (root, factory) {
  const node = typeof module === "object" && module.exports;
  const api = factory(
    root.DS.Algorithms,
    node ? require("../experiment.js") : root.DS.Experiments,
  );
  if (node) module.exports = api;
  root.DS.ChapterModules = root.DS.ChapterModules || {};
  root.DS.ChapterModules["graph"] = api;
})(globalThis, function (A, helpers) {
  "use strict";
  const { defineExperiment } = helpers;
  const graphPreset = () => A.graph.sampleGraph();
  const chapter = {
    id: "graph",
    no: "04",
    title: "图",
    subtitle: "扩展边界与路径松弛",
  };
  const experiments = [
    defineExperiment({
      id: "bfs",
      chapter: chapter.id,
      title: "图的广度优先搜索",
      visualizer: "graph",
      tag: "队列",
      difficulty: "进阶",
      code: [
        "void BFS(Graph G, int v) {",
        "  visit(v); visited[v] = true; EnQueue(Q, v);",
        "  while (!IsEmpty(Q)) {",
        "    DeQueue(Q, v);",
        "    for (w = FirstNeighbor(G, v); w >= 0; w = NextNeighbor(G,v,w))",
        "      if (!visited[w]) { visit(w); visited[w]=true; EnQueue(Q,w); }",
        "  }",
        "}",
      ],
      generator: A.graph.bfs,
      preset: () => [graphPreset(), "A"],
      explain: {
        goal: "从起点出发按由近及远的层次逐层扩展，访问其所在连通分量的全部顶点。",
        inputs: "图 G（邻接表或邻接矩阵）与起始顶点 v；需要 visited 数组标记已访问顶点。",
        steps: [
          "访问起点 v，置 visited[v] = true，并把 v 入队。",
          "循环判队空：若队列为空，遍历结束（终止条件）。",
          "队头顶点 v 出队，依次检查它的所有邻接点 w。",
          "若 w 尚未访问，则访问 w、置 visited[w] = true，并把 w 入队。",
          "若 w 已访问则跳过，继续检查 v 的下一个邻接点。",
          "重复第 2～5 步，直到队列为空，得到从 v 出发的层次遍历序列。",
          "图不连通时，再从未访问顶点中另选起点重启 BFS，才能覆盖所有连通分量。",
        ],
        keys: [
          "借助<b>队列</b>逐层扩展：先入队的顶点离起点更近，无权图中即最短路径层次。",
          "邻接表时间 O(V+E)、邻接矩阵 O(V²)，空间 O(V)；遍历序列不唯一。",
          "不连通图必须多次调用 BFS，否则只能访问起点所在的连通分量。",
        ],
        cost: "邻接表 O(V+E) · 邻接矩阵 O(V²) · 空间 O(V)",
      },
    }),
    defineExperiment({
      id: "dfs",
      chapter: chapter.id,
      title: "图的深度优先搜索",
      visualizer: "graph",
      tag: "递归回溯",
      difficulty: "进阶",
      code: [
        "void DFS(Graph G, int v) {",
        "  visited[v] = true;",
        "  visit(v);",
        "  for (w = FirstNeighbor(G,v); w >= 0;",
        "       w = NextNeighbor(G,v,w))",
        "    if (!visited[w]) DFS(G,w);",
        "  // 回溯到上一层",
        "}",
      ],
      generator: A.graph.dfs,
      preset: () => [graphPreset(), "A"],
      explain: {
        goal: "从起点出发沿一条路径尽量深入，无路可走时回溯，访问其所在连通分量的全部顶点。",
        inputs: "图 G（邻接表或邻接矩阵）与起始顶点 v；需要 visited 数组标记已访问顶点。",
        steps: [
          "从起点 v 出发，置 visited[v] = true 并访问 v。",
          "取 v 的第一个邻接点 w。",
          "若 w 未被访问，则以 w 为新起点递归执行 DFS，继续深入。",
          "若 w 已访问，则跳过它，沿邻接表取 v 的下一个邻接点继续检查。",
          "当 v 的所有邻接点都检查完毕，函数返回，回溯到上一层调用。",
          "回到上一层后继续处理该层尚未检查的邻接点，直到起点的邻接点全部处理完。",
          "图不连通时，再从未访问顶点重启 DFS，直到所有顶点都被标记。",
        ],
        keys: [
          "借助<b>递归栈</b>实现：优先深入未访问邻接点，走不通才回溯。",
          "邻接表 O(V+E)、邻接矩阵 O(V²)，递归栈空间最坏 O(V)。",
          "DFS 序列取决于邻接点的检查次序；可用于求连通分量、判断有向图是否有环。",
        ],
        cost: "邻接表 O(V+E) · 邻接矩阵 O(V²) · 空间 O(V)",
      },
    }),
    defineExperiment({
      id: "prim",
      chapter: chapter.id,
      title: "Prim 最小生成树",
      visualizer: "graph",
      tag: "顶点扩展",
      difficulty: "进阶",
      code: [
        "void Prim(Graph G, int start) {",
        "  AddVertex(start);",
        "  while (T.vexnum < G.vexnum) {",
        "    e = minEdge(T, G-T);",
        "    AddEdge(e);",
        "    AddVertex(e.outside);",
        "  }",
        "}",
      ],
      generator: A.graph.prim,
      preset: () => [graphPreset(), "A"],
      explain: {
        goal: "从任一顶点出发，每次选一条跨越已选顶点集合的最小边，逐步扩展出最小生成树。",
        inputs: "带权连通图 G 与起始顶点；记已选顶点集合为 T，其余顶点为候选集。",
        steps: [
          "任取起始顶点加入 T，此时生成树只有一个顶点、零条边。",
          "判断 T 是否已包含全部 n 个顶点；若已包含则构造完成（终止条件）。",
          "在「一端在 T 内、另一端在 T 外」的所有割边中，选择权值<b>最小</b>的一条。",
          "若不存在跨割边，说明图不连通，立即停止（只能得到生成森林）。",
          "把选中的边加入生成树，并把它的外部端点加入 T。",
          "重复第 2～5 步，每轮确定一条边，共选 n−1 条边后结束。",
          "每次只向 T 内引入一个新顶点，已加入的顶点与边不再重复考虑。",
        ],
        keys: [
          "按<b>顶点</b>扩展：每轮选连接树内外的最小割边，共选 n−1 条。",
          "朴素实现 O(V²)，适合稠密图；用最小堆维护候选边可优化到 O(E log V)。",
          "图不连通时选不到跨割边，必须判停，否则无法得到完整的最小生成树。",
        ],
        cost: "时间 O(V²) · 空间 O(V)",
      },
    }),
    defineExperiment({
      id: "kruskal",
      chapter: chapter.id,
      title: "Kruskal 最小生成树",
      visualizer: "graph",
      tag: "边集贪心",
      difficulty: "进阶",
      code: [
        "void Kruskal(Graph G) {",
        "  SortEdgesByWeight(G);",
        "  for (Edge e : edges) {",
        "    if (Find(e.u) != Find(e.v)) {",
        "      AddEdge(e);",
        "      Union(e.u, e.v);",
        "    } else Skip(e);",
        "  }",
        "}",
      ],
      generator: A.graph.kruskal,
      preset: () => [graphPreset()],
      explain: {
        goal: "按边权从小到大逐条考察，在不形成回路的前提下选出 n−1 条边组成最小生成树。",
        inputs: "带权无向图 G 的边集 E 与 n 个顶点；需要并查集维护各顶点的连通关系。",
        steps: [
          "把所有边按权值从小到大排序，得到有序边表。",
          "初始化并查集：每个顶点各自构成一个独立的集合。",
          "按顺序取出下一条权值最小的边 e = (u, v)。",
          "用 Find 判断 u、v 是否属于同一集合：相同则这条边会形成<b>回路</b>，直接舍弃。",
          "若属于不同集合，把边 e 加入生成树，并用 Union 合并 u、v 所在的两个集合。",
          "重复第 3～5 步；当已选边数达到 n−1 条时提前结束。",
          "若边表扫描完毕仍不足 n−1 条，说明图不连通，得到的是最小生成森林。",
        ],
        keys: [
          "按<b>边权递增</b>贪心，用并查集判回路，选够 n−1 条边即得最小生成树。",
          "时间 O(E log E) 主要花在排序上，适合稀疏图；空间 O(V+E)。",
          "与 Prim 的顶点扩展不同，Kruskal 的候选边可分散在多个连通分量中。",
        ],
        cost: "时间 O(E log E) · 空间 O(V+E)",
      },
    }),
    defineExperiment({
      id: "dijkstra",
      chapter: chapter.id,
      title: "Dijkstra 最短路径",
      visualizer: "graph",
      tag: "松弛",
      difficulty: "进阶",
      code: [
        "void Dijkstra(Graph G, int s) {",
        "  dist[s] = 0;",
        "  for (int i = 0; i < G.vexnum; i++) {",
        "    v = 未确定顶点中 dist 最小者; final[v] = true;",
        "    for (w = FirstNeighbor(G, v); w >= 0; w = NextNeighbor(G,v,w))",
        "      if (!final[w] && dist[v]+G[v][w] < dist[w])",
        "        dist[w] = dist[v] + G[v][w];",
        "  }",
        "}",
      ],
      generator: A.graph.dijkstra,
      preset: () => [graphPreset(), "A"],
      explain: {
        goal: "求源点到其余各顶点的最短路径长度，并可通过前驱数组还原具体路径。",
        inputs: "带权图 G（本实现要求边权非负）与源点 s；需要 dist 数组、final 标记和前驱数组。",
        steps: [
          "初始化：dist[s] = 0，其余顶点的 dist 置为 ∞，所有顶点的 final 均为 false。",
          "在未确定（final = false）的顶点中，选出 dist 值<b>最小</b>的顶点 v。",
          "把 v 标记为已确定 final[v] = true，此时 dist[v] 就是源点到 v 的最短距离。",
          "松弛 v 的每个邻接点 w：若 final[w] = false 且 dist[v] + 边权 < dist[w]，则更新 dist[w] 并记前驱为 v。",
          "若选出的最小 dist 为 ∞，说明剩余顶点均不可达，可以提前结束。",
          "重复第 2～4 步，直到 n 个顶点全部确定或提前结束。",
          "算法结束时 dist 给出最短距离，沿前驱指针回溯即可还原路径。",
        ],
        keys: [
          "每轮先确定<b>最小 dist</b> 的顶点，再用它松弛邻居；已确定顶点的 dist 不会再更新。",
          "时间 O(V²)，用优先队列可优化到 O(E log V)；要求边权非负，负权边应改用 Bellman-Ford。",
          "最小 dist 为 ∞ 时必须提前退出，否则会把不可达顶点的距离误当作已确定。",
        ],
        cost: "时间 O(V²) · 堆优化 O(E log V) · 空间 O(V)",
      },
    }),
    defineExperiment({
      id: "floyd",
      chapter: chapter.id,
      title: "Floyd 最短路径",
      visualizer: "matrix",
      tag: "距离矩阵",
      difficulty: "进阶",
      code: [
        "void Floyd(Graph G) {",
        "  A = G.adjacencyMatrix;",
        "  for (k = 0; k < n; k++)",
        "    for (i = 0; i < n; i++)",
        "      for (j = 0; j < n; j++)",
        "        A[i][j] = min(A[i][j],",
        "                      A[i][k] + A[k][j]);",
        "}",
      ],
      generator: A.graph.floyd,
      preset: () => [graphPreset()],
      explain: {
        goal: "用动态规划求出图中每一对顶点之间的最短路径长度。",
        inputs: "含 n 个顶点的图的邻接矩阵；允许负权边，但不允许负权回路。",
        steps: [
          "用邻接矩阵初始化距离矩阵 A：A[i][j] 取直接边权，对角线 A[i][i] = 0，无边取 ∞。",
          "令中间顶点 k 从 0 取到 n−1，依次允许编号不超过 k 的顶点参与中转。",
          "对每一对起点 i 与终点 j，比较原值 A[i][j] 与经 k 中转的 A[i][k] + A[k][j]。",
          "若经 k 中转更短，则把 A[i][j] 更新为 A[i][k] + A[k][j]。",
          "i、j 双重循环扫描完一轮后 k 增 1，重复第 3～4 步。",
          "k 遍历完成后，A[i][j] 即为 i 到 j 的全局最短路径长度。",
          "若出现 A[i][i] < 0，说明存在<b>负权回路</b>，最短路径无定义。",
        ],
        keys: [
          "三重循环中 k（中间顶点）必须放在<b>最外层</b>，否则中转结果不正确。",
          "初始矩阵对角线 A[i][i] = 0；可处理负权边，不能处理负权回路。",
          "时间 O(V³)、空间 O(V²)，适合顶点较少、需要全源最短路径的场合。",
        ],
        cost: "时间 O(V³) · 空间 O(V²)",
      },
    }),
    defineExperiment({
      id: "topological",
      chapter: chapter.id,
      title: "拓扑排序",
      visualizer: "graph",
      tag: "入度归零",
      difficulty: "进阶",
      code: [
        "void TopologicalSort(Graph G) {",
        "  EnQueue(all indegree == 0);",
        "  while (!IsEmpty(Q)) {",
        "    DeQueue(Q, v); output(v);",
        "    for (Edge v->w) {",
        "      if (--indegree[w] == 0) EnQueue(Q,w);",
        "    }",
        "}",
      ],
      generator: A.graph.topological,
      preset: () => [A.graph.sampleDag()],
      explain: {
        goal: "对无环有向图给出线性序列，使每条有向边都从前驱指向序列中更晚出现的顶点。",
        inputs: "有向图 G（邻接表）与各顶点的入度数组 indegree；存在有向回路时不存在拓扑序列。",
        steps: [
          "统计每个顶点的入度，把所有入度为 0 的顶点入队。",
          "判断队列是否为空：为空则排序结束（终止条件）。",
          "队头顶点 v 出队，并追加到拓扑序列中输出。",
          "依次删除 v 的每条出边 v→w，把 w 的入度减 1。",
          "若 w 的入度恰好减为 0，说明它的全部前驱都已输出，把 w 入队。",
          "重复第 2～5 步，直到队列为空，得到完整的拓扑序列。",
          "若输出的顶点数少于 n，说明图中存在<b>有向回路</b>，不存在拓扑序列。",
        ],
        keys: [
          "每次输出一个<b>入度为 0</b> 的顶点，并把其出边终点的入度减 1。",
          "拓扑序列通常不唯一；有向图存在回路时，无法完成拓扑排序。",
          "时间 O(V+E)、空间 O(V)；把队列换成栈同样得到合法的拓扑序列。",
        ],
        cost: "时间 O(V+E) · 空间 O(V)",
      },
    }),
    defineExperiment({
      id: "critical-path",
      chapter: chapter.id,
      title: "关键路径",
      visualizer: "graph",
      tag: "零时差",
      difficulty: "进阶",
      code: [
        "void CriticalPath(AOE G) {",
        "  topo = TopologicalSort(G);",
        "  ve[source] = 0;",
        "  for (v : topo) updateEarliest(v);",
        "  vl[sink] = ve[sink];",
        "  for (v : reverse(topo)) updateLatest(v);",
        "  if (e(activity) == l(activity)) markCritical();",
        "}",
      ],
      generator: A.graph.criticalPath,
      preset: () => [A.graph.sampleDag()],
      explain: {
        goal: "在 AOE 网中求出完成工程的最短工期，并找出决定工期的关键活动组成的路径。",
        inputs: "带权有向无环图（顶点为事件、弧为活动、权值为持续时间）；先求拓扑序列，有环则无关键路径。",
        steps: [
          "对 AOE 网求<b>拓扑序列</b>，同时判断是否存在有向回路。",
          "初始化事件最早发生时间：源点的 ve(源点) = 0，其余顶点按拓扑序正推。",
          "按拓扑序处理每个事件 v：对每条弧 v→w，若 ve(v) + 权值 > ve(w)，则用该较大值更新 ve(w)。",
          "所有事件处理完后，ve 的最大值即工程总工期；汇点的最迟发生时间 vl(汇点) = ve(汇点)。",
          "按逆拓扑序反推：对每条弧 v→w，令 vl(v) = min(vl(v), vl(w) − 权值)。",
          "对每条活动 a = v→w 计算最早开始时间 e(a) = ve(v) 与最迟开始时间 l(a) = vl(w) − 权值。",
          "若 e(a) == l(a)（<b>时差为 0</b>），该活动为关键活动；由关键活动组成的路径即关键路径。",
        ],
        keys: [
          "正推取<b>最大</b>（ve(w) = max(ve(v)+权值)），反推取最小（vl(v) = min(vl(w)−权值)）。",
          "关键活动的 e = l、时差为 0；关键路径可能不止一条，工期等于汇点的 ve。",
          "必须按拓扑序、逆拓扑序计算；缩短某个关键活动可能改变关键路径。",
        ],
        cost: "时间 O(V+E) · 空间 O(V)",
      },
    }),
  ];
  return { chapter, experiments };
});
