(function (root, factory) {
  const node = typeof module === "object" && module.exports;
  const api = factory(
    root.DS.Algorithms,
    node ? require("../experiment.js") : root.DS.Experiments,
  );
  if (node) module.exports = api;
  root.DS.ChapterModules = root.DS.ChapterModules || {};
  root.DS.ChapterModules["search"] = api;
})(globalThis, function (A, helpers) {
  "use strict";
  const { defineExperiment } = helpers;
  const chapter = {
    id: "search",
    no: "05",
    title: "查找",
    subtitle: "有序区间逐步收缩",
  };
  const experiments = [
    defineExperiment({
      id: "binary-search",
      chapter: chapter.id,
      title: "折半查找",
      visualizer: "array",
      tag: "区间收缩",
      difficulty: "基础",
      code: [
        "int BinarySearch(int A[], int n, int key) {",
        "  int low = 0, high = n - 1;",
        "  while (low <= high) {",
        "    int mid = (low + high) / 2;",
        "    if (A[mid] == key) return mid;",
        "    if (A[mid] < key)",
        "      low = mid + 1;",
        "    else",
        "      high = mid - 1;",
        "  }",
        "  return -1;",
        "}",
      ],
      generator: A.search.binarySearch,
      preset: () => [[7, 13, 19, 28, 36, 45, 57, 68], 45],
      explain: {
        goal: "在有序顺序表中反复折半缩小查找区间，定位与 key 相等的元素或判定查找失败。",
        inputs: "含 n 个元素、按关键字递增有序的顺序表 A 与目标关键字 key。",
        steps: [
          "初始化查找区间：low = 0、high = n − 1。",
          "若 low > high，则区间为空，查找失败，返回 −1。",
          "取中点 mid = ⌊(low + high) / 2⌋，比较 A[mid] 与 key。",
          "若 A[mid] == key，查找成功，返回下标 mid。",
          "若 A[mid] < key，说明目标只可能在右半区，令 low = mid + 1。",
          "若 A[mid] > key，说明目标只可能在左半区，令 high = mid − 1。",
          "重复第 2～6 步，每次比较都把查找区间缩小一半。",
        ],
        keys: [
          "仅适用于<b>有序且顺序存储</b>的表；链表不能随机访问，无法折半查找。",
          "比较次数不超过 ⌈log₂(n+1)⌉，时间 O(log n)、空间 O(1)。",
          "区间端点更新为 mid ± 1（mid 已比较过），写成 mid 会陷入死循环。",
        ],
        cost: "时间 O(log n) · 空间 O(1)",
      },
    }),
    defineExperiment({
      id: "bst-insert",
      chapter: chapter.id,
      title: "BST 插入",
      visualizer: "tree",
      tag: "有序树",
      difficulty: "基础",
      code: [
        "void InsertBST(BiTree &T, Key key) {",
        "  if (T == NULL) createNode(T,key);",
        "  else {",
        "    // 比较当前结点",
        "    if (key < T->key)",
        "      InsertBST(T->lchild,key);",
        "    else InsertBST(T->rchild,key);",
        "  }",
        "}",
      ],
      generator: A.search.bstInsert,
      preset: () => [[45, 24, 53, 12, 37, 93, 30]],
      explain: {
        goal: "把关键字按二叉排序树的有序性插入到合适位置，使中序序列保持递增。",
        inputs: "一棵二叉排序树（可为空树）与待插入关键字 key；重复关键字按约定跳过或归入右子树。",
        steps: [
          "从根结点开始：若当前树为空（T = NULL），生成含 key 的新结点并作为根返回。",
          "若 key < T->key，说明应插入左子树，递归处理左孩子。",
          "若 key > T->key，说明应插入右子树，递归处理右孩子。",
          "若 key 与当前结点相等，按约定不再重复插入（本演示把相等关键字归入右侧）。",
          "递归到空位置时创建新结点，挂到父结点对应的孩子指针上。",
          "依次插入全部关键字后，中序遍历该树得到的序列必然<b>递增有序</b>。",
          "插入次序不同会得到不同形态的 BST；按有序序列插入会退化成单支树。",
        ],
        keys: [
          "插入的新结点总是成为<b>叶子</b>，不需要移动已有结点。",
          "平均查找长度 O(log n)，最坏（有序插入）退化为 O(n)。",
          "只有中序序列递增的二叉树才是二叉排序树；左子树所有关键字均小于根。",
        ],
        cost: "平均 O(log n) · 最坏 O(n) · 空间 O(h)",
      },
    }),
    defineExperiment({
      id: "avl-rotations",
      chapter: chapter.id,
      title: "AVL 四类旋转",
      visualizer: "tree",
      tag: "平衡调整",
      difficulty: "基础",
      code: [
        "void Rebalance(AVLTree &T) {",
        "  updateBalanceFactor(T);",
        "  if (T->bf == 2) {",
        "    // 检测失衡类型",
        "    if (T->lchild->bf >= 0) R_Rotate(T);",
        "    else LR_Rotate(T);",
        "  } else if (T->bf == -2) L_Rotate(T);",
        "  // RL 情形先右旋孩子再左旋",
        "}",
      ],
      generator: A.search.avlRotations,
      preset: () => [],
      explain: {
        goal: "演示 AVL 树失衡的四种类型，并用相应的左旋、右旋组合恢复平衡。",
        inputs: "依次插入关键字形成的二叉排序树；失衡结点的平衡因子 bf 取值为 2 或 −2。",
        steps: [
          "插入新结点后，沿插入路径自下而上更新各结点的<b>平衡因子</b>（左高为正、右高为负）。",
          "若某结点 bf = ±2，则该结点为最小失衡子树的根，需要旋转调整。",
          "<b>LL 型</b>（新结点在左孩子的左子树，bf = 2 且左孩子 bf ≥ 0）：对失衡结点做一次右旋。",
          "<b>RR 型</b>（新结点在右孩子的右子树，bf = −2 且右孩子 bf ≤ 0）：对失衡结点做一次左旋。",
          "<b>LR 型</b>（新结点在左孩子的右子树，bf = 2 且左孩子 bf < 0）：先对左孩子左旋，再对失衡结点右旋。",
          "<b>RL 型</b>（新结点在右孩子的左子树，bf = −2 且右孩子 bf > 0）：先对右孩子右旋，再对失衡结点左旋。",
          "旋转后取三个相关结点的中间者作为子树新根，其余两个分列左右孩子，该子树高度恢复到插入前。",
        ],
        keys: [
          "按「新结点相对失衡结点的位置」判定类型：LL / RR 单旋，LR / RL 双旋（先旋孩子再旋失衡结点）。",
          "左旋与右旋互为镜像：右旋使左孩子上升，左旋使右孩子上升；旋转不改变中序序列。",
          "插入最多触发一次旋转（以最小失衡子树为界）；删除后可能沿路径多次调整。",
        ],
        cost: "查找/插入/删除 O(log n) · 空间 O(n)",
      },
    }),
    defineExperiment({
      id: "hash-chaining",
      chapter: chapter.id,
      title: "散列表冲突处理",
      visualizer: "hash",
      tag: "链地址法",
      difficulty: "基础",
      code: [
        "void InsertHash(HashTable &H, Key key) {",
        "  int index = key % H.size;",
        "  // 计算散列地址",
        "  if (H.bucket[index] != NULL)",
        "    // 发生冲突，使用链地址法",
        "    append(H.bucket[index], key);",
        "  else H.bucket[index] = new Node(key);",
        "  H.count++;",
        "}",
      ],
      generator: A.search.hashDemo,
      preset: () => [[19, 14, 23, 1, 68, 20], 7],
      explain: {
        goal: "用散列函数定位桶，并把散列地址相同的冲突关键字串成链表，完成插入与查找。",
        inputs: "表长（桶数）m 与一组关键字；散列函数取 H(key) = key mod m，冲突用链地址法处理。",
        steps: [
          "建立长度为 m 的散列表：每个地址对应一个桶，初始均为空链表。",
          "对每个待插入关键字 key，计算散列地址 index = key mod m。",
          "若该桶为空，直接以 key 生成结点放入桶中。",
          "若该桶非空，说明发生<b>冲突</b>，把 key 追加到该桶的冲突链表中。",
          "每插入一个关键字，元素个数 count 加 1，装填因子 α = count / m 随之增大。",
          "查找关键字时先算散列地址，再沿该桶的链表逐个比较；插入前也应先查重。",
          "全部关键字插入完毕后，各桶的链表长度反映该地址下的冲突规模。",
        ],
        keys: [
          "装填因子 α = n / m（元素数 / 表长），α 越大冲突越多、平均查找长度越长。",
          "链地址法查找成功比较次数约 1 + α/2，失败约 α；最坏全部同义词同桶，退化为 O(n)。",
          "同义词按插入次序挂在链表上，新结点可头插也可尾插；链地址法删除方便、无需探测。",
        ],
        cost: "平均 O(1+α) · 最坏 O(n) · 空间 O(n+m)",
      },
    }),
  ];
  return { chapter, experiments };
});
