(function (root, factory) {
  const node = typeof module === "object" && module.exports;
  const api = factory(
    root.DS.Algorithms,
    node ? require("../experiment.js") : root.DS.Experiments,
  );
  if (node) module.exports = api;
  root.DS.ChapterModules = root.DS.ChapterModules || {};
  root.DS.ChapterModules["tree"] = api;
})(globalThis, function (A, helpers) {
  "use strict";
  const { defineExperiment } = helpers;
  const treePreset = () => A.tree.sampleTree();
  const chapter = {
    id: "tree",
    no: "03",
    title: "树",
    subtitle: "递归路径与访问时机",
  };
  const experiments = [
    defineExperiment({
      id: "preorder",
      chapter: chapter.id,
      title: "二叉树先序遍历",
      visualizer: "tree",
      tag: "根左右",
      difficulty: "进阶",
      code: [
        "void Traverse(BiTree T) {",
        "  if (T != NULL) {",
        "    visit(T);        // 先序位置",
        "    Traverse(T->lchild);",
        "    visit(T);        // 中序位置",
        "    Traverse(T->rchild);",
        "    visit(T);        // 后序位置",
        "  }",
        "}",
      ],
      generator: A.tree.traverse,
      preset: () => [treePreset(), "pre"],
      explain: {
        goal: "按「根 → 左 → 右」的次序访问二叉树的所有结点，得到先序序列。",
        inputs: "二叉树根结点 T；结点为空表示到达递归边界，空树无需访问。",
        steps: [
          "进入结点：若 T = NULL（空树或空子树），直接返回上一层。",
          "在<b>进入结点时</b>访问根结点 T，把它的值加入输出序列。",
          "递归遍历 T 的左子树。",
          "左子树全部处理完后，递归遍历 T 的右子树。",
          "右子树处理完毕，函数回溯到上一层，继续处理祖先结点尚未完成的分支。",
          "重复上述过程直到根结点的右子树也处理完，输出「根左右」次序的先序序列。",
        ],
        keys: [
          "先序在进入结点时访问：根最先输出，因此先序序列的首个元素必为根。",
          "时间 O(n)，每个结点恰好访问一次；递归栈空间 O(h)，单支树最坏 O(n)。",
          "先序、中序、后序共用同一递归模板，差别只在<b>访问时机</b>。",
        ],
        cost: "时间 O(n) · 空间 O(h)，最坏 O(n)",
      },
    }),
    defineExperiment({
      id: "inorder",
      chapter: chapter.id,
      title: "二叉树中序遍历",
      visualizer: "tree",
      tag: "左根右",
      difficulty: "进阶",
      code: [
        "void Traverse(BiTree T) {",
        "  if (T != NULL) {",
        "    visit(T);        // 先序位置",
        "    Traverse(T->lchild);",
        "    visit(T);        // 中序位置",
        "    Traverse(T->rchild);",
        "    visit(T);        // 后序位置",
        "  }",
        "}",
      ],
      generator: A.tree.traverse,
      preset: () => [treePreset(), "in"],
      explain: {
        goal: "按「左 → 根 → 右」的次序访问二叉树的所有结点，得到中序序列。",
        inputs: "二叉树根结点 T；结点为空表示到达递归边界，空树无需访问。",
        steps: [
          "进入结点：若 T = NULL（空树或空子树），直接返回上一层。",
          "先递归遍历 T 的左子树，当前结点暂不访问。",
          "左子树返回后，在<b>中序位置</b>访问结点 T，把它的值加入输出序列。",
          "再递归遍历 T 的右子树。",
          "右子树处理完毕，回溯到上一层，重复「先左、后根、再右」的过程。",
          "所有结点访问完毕，得到中序序列；对二叉排序树该序列必递增有序。",
        ],
        keys: [
          "根结点位于左、右子树序列之间；二叉排序树的中序序列必<b>递增有序</b>。",
          "时间 O(n)，递归栈空间 O(h)；左子树为空时立即访问根，不要漏掉这一步。",
          "与先序、后序的遍历路径完全相同，差别只在访问时机。",
        ],
        cost: "时间 O(n) · 空间 O(h)，最坏 O(n)",
      },
    }),
    defineExperiment({
      id: "postorder",
      chapter: chapter.id,
      title: "二叉树后序遍历",
      visualizer: "tree",
      tag: "左右根",
      difficulty: "进阶",
      code: [
        "void Traverse(BiTree T) {",
        "  if (T != NULL) {",
        "    visit(T);        // 先序位置",
        "    Traverse(T->lchild);",
        "    visit(T);        // 中序位置",
        "    Traverse(T->rchild);",
        "    visit(T);        // 后序位置",
        "  }",
        "}",
      ],
      generator: A.tree.traverse,
      preset: () => [treePreset(), "post"],
      explain: {
        goal: "按「左 → 右 → 根」的次序访问二叉树的所有结点，得到后序序列。",
        inputs: "二叉树根结点 T；结点为空表示到达递归边界，空树无需访问。",
        steps: [
          "进入结点：若 T = NULL（空树或空子树），直接返回上一层。",
          "先递归遍历 T 的左子树。",
          "左子树返回后，再递归遍历 T 的右子树。",
          "左、右子树都处理完后，在<b>后序位置</b>访问结点 T。",
          "访问后回溯到上一层，继续完成祖先结点右子树中尚未处理的部分。",
          "根结点最后被访问，输出「左右根」次序的后序序列。",
        ],
        keys: [
          "后序序列的最后一个元素必为根结点；适合先处理子树再汇总（如求树高、释放结点）。",
          "时间 O(n)，空间 O(h)；已知后序与中序可唯一确定二叉树，仅知先序与后序不能。",
          "必须等左、右子树都返回后再访问根，提前访问会破坏后序定义。",
        ],
        cost: "时间 O(n) · 空间 O(h)，最坏 O(n)",
      },
    }),
    defineExperiment({
      id: "level-order",
      chapter: chapter.id,
      title: "二叉树层序遍历",
      visualizer: "tree",
      tag: "队列",
      difficulty: "进阶",
      code: [
        "void LevelOrder(BiTree T) {",
        "  EnQueue(Q, T);",
        "  while (!IsEmpty(Q)) {",
        "    DeQueue(Q, p); visit(p);",
        "    if (p->lchild) EnQueue(Q, p->lchild);",
        "    if (p->rchild) EnQueue(Q, p->rchild);",
        "  }",
        "}",
      ],
      generator: A.tree.levelOrder,
      preset: () => [treePreset()],
      explain: {
        goal: "借助队列按层访问二叉树，自上而下、每层自左向右输出所有结点。",
        inputs: "二叉树根结点 T；空树时队列为空，遍历直接结束。",
        steps: [
          "先判空：若树为空则没有结点入队，遍历直接结束。",
          "把根结点入队。",
          "循环判队空：若队列为空，说明所有结点已处理完，遍历结束（终止条件）。",
          "队头结点出队并访问，把它加入输出序列。",
          "若该结点有左孩子，把左孩子入队。",
          "若该结点有右孩子，把右孩子入队。",
          "重复第 3～6 步，先入队的结点先出队，输出序列自然按层排列。",
        ],
        keys: [
          "用<b>队列</b>而不是递归实现按层扩展，同层结点按从左到右的次序入队。",
          "时间 O(n)，队列空间 O(w)（w 为最大层宽），最坏 O(n)。",
          "左右孩子必须先左后右入队，顺序颠倒会破坏同层输出次序。",
        ],
        cost: "时间 O(n) · 空间 O(w)，最坏 O(n)",
      },
    }),
    defineExperiment({
      id: "huffman",
      chapter: chapter.id,
      title: "哈夫曼树构造",
      visualizer: "tree",
      tag: "最小权合并",
      difficulty: "进阶",
      code: [
        "while (forest.size > 1) {",
        "  sort(forest);",
        "  left = popMin(); right = popMin();",
        "  parent = new Node(left.w + right.w);",
        "  parent->left = left; parent->right = right;",
        "  push(forest, parent);",
        "}",
      ],
      generator: A.tree.huffman,
      preset: () => [[5, 9, 12, 13, 16, 45]],
      explain: {
        goal: "反复合并权值最小的两棵树，构造带权路径长度 WPL 最小的哈夫曼树。",
        inputs: "n 个权值，各自先构成只有根结点的单结点树；叶子数 n 至少为 1。",
        steps: [
          "把每个权值看作一棵独立的单结点树，n 棵树组成森林。",
          "若森林中只剩一棵树，构造结束，它就是哈夫曼树（终止条件）。",
          "否则在森林中选出根权值<b>最小</b>的两棵树。",
          "以这两棵树为左、右子树合并，新根结点的权值等于二者权值之和。",
          "从森林中删去这两棵树，把新树加入森林。",
          "重复第 3～5 步，每轮森林减少一棵树，共合并 n−1 次。",
          "若最小权值出现并列，任取两棵合并不影响最终的 WPL。",
        ],
        keys: [
          "每次贪心合并两个最小权值，保证 WPL = Σ 权值 × 路径长度 最小。",
          "哈夫曼树不存在度为 1 的结点：n 个叶子的哈夫曼树共 2n−1 个结点。",
          "演示按排序取最小，复杂度为 O(n²) 级；用小根堆维护可做到 O(n log n)。",
        ],
        cost: "排序实现 O(n²) · 小根堆 O(n log n) · 空间 O(n)",
      },
    }),
    defineExperiment({
      id: "union-find",
      chapter: chapter.id,
      title: "并查集",
      visualizer: "tree",
      tag: "集合合并",
      difficulty: "进阶",
      code: [
        "void Union(int a, int b) {",
        "  int ra = Find(a), rb = Find(b);",
        "  // 查找两个集合的根",
        "  if (ra != rb)",
        "    parent[rb] = ra;",
        "  // 可配合路径压缩",
        "}",
      ],
      generator: A.tree.unionFindDemo,
      preset: () => [
        ["A", "B", "C", "D", "E", "F", "G"],
        [
          ["B", "A"],
          ["C", "B"],
          ["D", "C"],
          ["A", "E"],
          ["F", "E"],
          ["G", "F"],
        ],
      ],
      explain: {
        goal: "维护不相交集合：查询元素所属集合的根，并把两个集合合并为一个。",
        inputs: "n 个元素各自初始为独立集合（parent[x] = x），以及若干 Union(a, b) 操作。示例为 7 个元素、6 次合并，其中一次 Find 会触发路径压缩。",
        steps: [
          "初始化：每个元素的双亲指针指向自己，各自构成一个集合。",
          "执行 Find(a)：沿 parent 指针逐级上溯，直到某结点的双亲是它自己，该结点即集合的根。",
          "执行 Find(b)：用同样方法找到 b 所属集合的根。",
          "若 ra == rb，说明 a、b 已在同一集合，本次 Union 不做任何操作。",
          "若 ra != rb，把一个根的双亲指向另一个根（如 parent[rb] = ra），两个集合合并。",
          "Find 时可把沿途结点直接挂到根上，即<b>路径压缩</b>：示例中 A→B→C→D 的长链被压平成 A、B、C 都直接指向根。",
          "全部操作结束后，parent 数组与各集合的根反映最终的集合划分。",
        ],
        keys: [
          "合并只能把一个集合的<b>根</b>挂到另一个根上，不能让两个非根结点直接相连。",
          "不优化时树高可达 O(n)；路径压缩把 Find 路径上的结点直接挂到根，使后续 Find 近乎 O(1)。",
          "Find(a) == Find(b) 可判断两元素是否同属一个集合（如 Kruskal 判回路）。",
        ],
        cost: "朴素 O(n) · 路径压缩+按秩合并 近似 O(α(n)) · 空间 O(n)",
      },
    }),
  ];
  return { chapter, experiments };
});
